#####
POST  http://localhost:5000/newuser HTTP/1.1
content-type: application/json

{"Email":"jermpro0@gmail.com", "Password":"Yash0607", "Name":"Yash" }


#####

POST  http://localhost:5000/login HTTP/1.1
content-type: application/json

{"Email":"jermpro0@gmail.com", "Password":"Yash0607"}


#####


GET   http://localhost:5000/User HTTP/1.1
Authorization: 
content-type: application/json


#####